CREATE DATABASE CSV_FINAL_ASSIGNMENT;
CREATE SCHEMA IF NOT EXISTS CSV;

/*########################  STAGE CREATION  ############################*/
CREATE OR REPLACE STAGE STG_CSV
  URL   = 's3://da-batch2-group1-capstone/CSV_FILES/'
  STORAGE_INTEGRATION = S3_STORAGE_INTEGRATION;

/*########################  FILE FORMAT CREATION  ############################*/
CREATE OR REPLACE FILE FORMAT FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('NULL');

CREATE OR REPLACE FILE FORMAT FF_RAW
  TYPE = CSV
  FIELD_DELIMITER = '\t'       -- entire line goes into one column
  SKIP_HEADER = 0              -- keep header if you want it
  FIELD_OPTIONALLY_ENCLOSED_BY = NONE;

/*########################  RAW TABLES CREATION  ############################*/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_PATIENTS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_ALLERGIES (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_CAREPLANS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS_TRANSACTIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_CONDITIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_DEVICES (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_ENCOUNTERS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_IMAGING_STUDIES (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_IMMUNIZATIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_MEDICATIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_OBSERVATIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_ORGANIZATIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYER_TRANSITIONS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYERS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_PROCEDURES (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_PROVIDERS (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.RAW_SUPPLIES (
  RAW_LINE       VARCHAR,  -- the entire comma-separated line from CSV
  SRC_FILENAME   VARCHAR,  -- file path/name
  SRC_ROW_NUMBER NUMBER    -- row number within the file (1-based)
);

/*########################  COPY INTO RAW_TABLES  ############################*/
-- PATIENTS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_PATIENTS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR                               AS RAW_LINE,
    METADATA$FILENAME                           AS SRC_FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER            AS SRC_ROW_NUMBER
  FROM @STG_CSV/patients.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- ALLERGIES
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_ALLERGIES (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR                               AS RAW_LINE,
    METADATA$FILENAME                           AS SRC_FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER            AS SRC_ROW_NUMBER
  FROM @STG_CSV/allergies.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- CAREPLANS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_CAREPLANS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/careplans.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- CLAIMS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/claims.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- CLAIMS_TRANSACTIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS_TRANSACTIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/claims_transactions.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- CONDITIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_CONDITIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/conditions.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- DEVICES
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_DEVICES (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/devices.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- ENCOUNTERS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_ENCOUNTERS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/encounters.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- IMAGING_STUDIES
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_IMAGING_STUDIES (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/imaging_studies.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- IMMUNIZATIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_IMMUNIZATIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/immunizations.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- MEDICATIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_MEDICATIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/medications.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- OBSERVATIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_OBSERVATIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/observations.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- ORGANIZATIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_ORGANIZATIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/organizations.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- PAYER_TRANSITIONS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYER_TRANSITIONS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/payer_transitions.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- PAYERS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYERS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/payers.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- PROCEDURES
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_PROCEDURES (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/procedures.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- PROVIDERS
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_PROVIDERS (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/providers.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

-- SUPPLIES
COPY INTO CSV_FINAL_ASSIGNMENT.CSV.RAW_SUPPLIES (RAW_LINE, SRC_FILENAME, SRC_ROW_NUMBER)
FROM (
  SELECT
    t.$1::VARCHAR,
    METADATA$FILENAME,
    METADATA$FILE_ROW_NUMBER::NUMBER
  FROM @STG_CSV/supplies.csv (FILE_FORMAT => FF_RAW) t
)
FILE_FORMAT = (FORMAT_NAME = FF_RAW)
ON_ERROR = 'CONTINUE';

/*########################  PARCING PROCEDURE  ############################*/
CREATE OR REPLACE FUNCTION CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(line STRING)
RETURNS VARIANT
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
HANDLER = 'parse'
AS
$$
import csv, io

def parse(line):
    # csv.reader handles quoted fields and embedded commas
    row = next(csv.reader(io.StringIO(line)))
    # Trim whitespace just in case
    return [s.strip() if isinstance(s, str) else s for s in row]
$$;

/*########################  BRONZE TABLES CREATION  ############################*/

/************************ALLERGIES**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.ALLERGIES (
  "START" VARCHAR, "STOP" VARCHAR, PATIENT VARCHAR, ENCOUNTER VARCHAR,
  CODE VARCHAR, SYSTEM VARCHAR, DESCRIPTION VARCHAR, TYPE VARCHAR, CATEGORY VARCHAR,
  REACTION1 VARCHAR, DESCRIPTION1 VARCHAR, SEVERITY1 VARCHAR,
  REACTION2 VARCHAR, DESCRIPTION2 VARCHAR, SEVERITY2 VARCHAR,
  SRC_FILENAME VARCHAR, SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.ALLERGIES
SELECT
  v[0]::STRING, v[1]::STRING, v[2]::STRING, v[3]::STRING,
  v[4]::STRING, v[5]::STRING, v[6]::STRING, v[7]::STRING, v[8]::STRING,
  v[9]::STRING, v[10]::STRING, v[11]::STRING,
  v[12]::STRING, v[13]::STRING, v[14]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_ALLERGIES r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************CAREPLANS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.CAREPLANS (
  Id VARCHAR,
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  REASONCODE VARCHAR,
  REASONDESCRIPTION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.CAREPLANS
SELECT
  v[0]::STRING,  -- Id
  v[1]::STRING,  -- START -> START_TIME
  v[2]::STRING,  -- STOP  -> STOP_TIME
  v[3]::STRING,  -- PATIENT
  v[4]::STRING,  -- ENCOUNTER
  v[5]::STRING,  -- CODE
  v[6]::STRING,  -- DESCRIPTION
  v[7]::STRING,  -- REASONCODE
  v[8]::STRING,  -- REASONDESCRIPTION
  r.SRC_FILENAME,
  r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_CAREPLANS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************CLAIMS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.CLAIMS (
  Id VARCHAR,
  PATIENTID VARCHAR,
  PROVIDERID VARCHAR,
  PRIMARYPATIENTINSURANCEID VARCHAR,
  SECONDARYPATIENTINSURANCEID VARCHAR,
  DEPARTMENTID VARCHAR,
  PATIENTDEPARTMENTID VARCHAR,
  DIAGNOSIS1 VARCHAR,
  DIAGNOSIS2 VARCHAR,
  DIAGNOSIS3 VARCHAR,
  DIAGNOSIS4 VARCHAR,
  DIAGNOSIS5 VARCHAR,
  DIAGNOSIS6 VARCHAR,
  DIAGNOSIS7 VARCHAR,
  DIAGNOSIS8 VARCHAR,
  REFERRINGPROVIDERID VARCHAR,
  APPOINTMENTID VARCHAR,
  CURRENTILLNESSDATE VARCHAR,
  SERVICEDATE VARCHAR,
  SUPERVISINGPROVIDERID VARCHAR,
  STATUS1 VARCHAR,
  STATUS2 VARCHAR,
  STATUSP VARCHAR,
  OUTSTANDING1 VARCHAR,
  OUTSTANDING2 VARCHAR,
  OUTSTANDINGP VARCHAR,
  LASTBILLEDDATE1 VARCHAR,
  LASTBILLEDDATE2 VARCHAR,
  LASTBILLEDDATEP VARCHAR,
  HEALTHCARECLAIMTYPEID1 VARCHAR,
  HEALTHCARECLAIMTYPEID2 VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.CLAIMS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,
  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,  v[10]::STRING, v[11]::STRING, v[12]::STRING, v[13]::STRING, v[14]::STRING,
  v[15]::STRING, v[16]::STRING, v[17]::STRING, v[18]::STRING, v[19]::STRING,
  v[20]::STRING, v[21]::STRING, v[22]::STRING,
  v[23]::STRING, v[24]::STRING, v[25]::STRING,
  v[26]::STRING, v[27]::STRING, v[28]::STRING,
  v[29]::STRING, v[30]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************CLAIMS_TRANSACTIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.CLAIMS_TRANSACTIONS (
  ID VARCHAR,
  CLAIMID VARCHAR,
  CHARGEID VARCHAR,
  PATIENTID VARCHAR,
  TYPE VARCHAR,
  AMOUNT VARCHAR,
  METHOD VARCHAR,
  FROMDATE VARCHAR,
  TODATE VARCHAR,
  PLACEOFSERVICE VARCHAR,
  PROCEDURECODE VARCHAR,
  MODIFIER1 VARCHAR,
  MODIFIER2 VARCHAR,
  DIAGNOSISREF1 VARCHAR,
  DIAGNOSISREF2 VARCHAR,
  DIAGNOSISREF3 VARCHAR,
  DIAGNOSISREF4 VARCHAR,
  UNITS VARCHAR,
  DEPARTMENTID VARCHAR,
  NOTES VARCHAR,
  UNITAMOUNT VARCHAR,
  TRANSFEROUTID VARCHAR,
  TRANSFERTYPE VARCHAR,
  PAYMENTS VARCHAR,
  ADJUSTMENTS VARCHAR,
  TRANSFERS VARCHAR,
  OUTSTANDING VARCHAR,
  APPOINTMENTID VARCHAR,
  LINENOTE VARCHAR,
  PATIENTINSURANCEID VARCHAR,
  FEESCHEDULEID VARCHAR,
  PROVIDERID VARCHAR,
  SUPERVISINGPROVIDERID VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.CLAIMS_TRANSACTIONS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,
  v[5]::STRING,  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,
  v[10]::STRING, v[11]::STRING, v[12]::STRING,
  v[13]::STRING, v[14]::STRING, v[15]::STRING, v[16]::STRING,
  v[17]::STRING, v[18]::STRING, v[19]::STRING, v[20]::STRING,
  v[21]::STRING, v[22]::STRING, v[23]::STRING, v[24]::STRING,
  v[25]::STRING, v[26]::STRING, v[27]::STRING, v[28]::STRING,
  v[29]::STRING, v[30]::STRING, v[31]::STRING, v[32]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_CLAIMS_TRANSACTIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;
/************************CONDITIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.CONDITIONS (
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.CONDITIONS
SELECT
  v[0]::STRING,  -- START 
  v[1]::STRING,  -- STOP  
  v[2]::STRING,  -- PATIENT
  v[3]::STRING,  -- ENCOUNTER
  v[4]::STRING,  -- CODE
  v[5]::STRING,  -- DESCRIPTION
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_CONDITIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************DEVICES**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.DEVICES (
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  UDI VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.DEVICES
SELECT
  v[0]::STRING,  -- START -> START_TIME
  v[1]::STRING,  -- STOP  -> STOP_TIME
  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_DEVICES r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************ENCOUNTERS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.ENCOUNTERS (
  Id VARCHAR,
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  ORGANIZATION VARCHAR,
  PROVIDER VARCHAR,
  PAYER VARCHAR,
  ENCOUNTERCLASS VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  BASE_ENCOUNTER_COST VARCHAR,
  TOTAL_CLAIM_COST VARCHAR,
  PAYER_COVERAGE VARCHAR,
  REASONCODE VARCHAR,
  REASONDESCRIPTION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.ENCOUNTERS
SELECT
  v[0]::STRING,  -- Id
  v[1]::STRING,  -- START -> START_TIME
  v[2]::STRING,  -- STOP  -> STOP_TIME
  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,
  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,
  v[10]::STRING, v[11]::STRING, v[12]::STRING,
  v[13]::STRING, v[14]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_ENCOUNTERS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************IMAGING_STUDIES**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.IMAGING_STUDIES (
  Id VARCHAR,
  DATE VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  SERIES_UID VARCHAR,
  BODYSITE_CODE VARCHAR,
  BODYSITE_DESCRIPTION VARCHAR,
  MODALITY_CODE VARCHAR,
  MODALITY_DESCRIPTION VARCHAR,
  INSTANCE_UID VARCHAR,
  SOP_CODE VARCHAR,
  SOP_DESCRIPTION VARCHAR,
  PROCEDURE_CODE VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.IMAGING_STUDIES
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,
  v[5]::STRING,  v[6]::STRING,
  v[7]::STRING,  v[8]::STRING,
  v[9]::STRING,  v[10]::STRING, v[11]::STRING, v[12]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_IMAGING_STUDIES r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************IMMUNIZATIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.IMMUNIZATIONS (
  DATE VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  BASE_COST VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.IMMUNIZATIONS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_IMMUNIZATIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;
/************************MEDICATIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.MEDICATIONS (
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  PAYER VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  BASE_COST VARCHAR,
  PAYER_COVERAGE VARCHAR,
  DISPENSES VARCHAR,
  TOTALCOST VARCHAR,
  REASONCODE VARCHAR,
  REASONDESCRIPTION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.MEDICATIONS
SELECT
  v[0]::STRING,  -- START -> START_TIME
  v[1]::STRING,  -- STOP  -> STOP_TIME
  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,
  v[5]::STRING,  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,
  v[9]::STRING,  v[10]::STRING, v[11]::STRING, v[12]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_MEDICATIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************OBSERVATIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.OBSERVATIONS (
  DATE VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CATEGORY VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  VALUE VARCHAR,
  UNITS VARCHAR,
  TYPE VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.OBSERVATIONS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,
  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_OBSERVATIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;
/************************ORGANIZATIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.ORGANIZATIONS (
  Id VARCHAR,
  NAME VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  ZIP VARCHAR,
  LAT VARCHAR,
  LON VARCHAR,
  PHONE VARCHAR,
  REVENUE VARCHAR,
  UTILIZATION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.ORGANIZATIONS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,
  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,  v[10]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_ORGANIZATIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************PATIENTS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.PATIENTS (
  Id VARCHAR,
  BIRTHDATE VARCHAR,
  DEATHDATE VARCHAR,
  SSN VARCHAR,
  DRIVERS VARCHAR,
  PASSPORT VARCHAR,
  PREFIX VARCHAR,
  "FIRST" VARCHAR,
  "LAST" VARCHAR,
  SUFFIX VARCHAR,
  MAIDEN VARCHAR,
  MARITAL VARCHAR,
  RACE VARCHAR,
  ETHNICITY VARCHAR,
  GENDER VARCHAR,
  BIRTHPLACE VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTY VARCHAR,
  FIPS VARCHAR,
  ZIP VARCHAR,
  LAT VARCHAR,
  LON VARCHAR,
  HEALTHCARE_EXPENSES VARCHAR,
  HEALTHCARE_COVERAGE VARCHAR,
  INCOME VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.PATIENTS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,
  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,  v[10]::STRING, v[11]::STRING,
  v[12]::STRING, v[13]::STRING, v[14]::STRING, v[15]::STRING, v[16]::STRING, v[17]::STRING,
  v[18]::STRING, v[19]::STRING, v[20]::STRING, v[21]::STRING, v[22]::STRING, v[23]::STRING, 
  v[24]::STRING, v[25]::STRING, v[26]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_PATIENTS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************PAYERS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.PAYERS (
  Id VARCHAR,
  NAME VARCHAR,
  OWNERSHIP VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE_HEADQUARTERED VARCHAR,
  ZIP VARCHAR,
  PHONE VARCHAR,
  AMOUNT_COVERED VARCHAR,
  AMOUNT_UNCOVERED VARCHAR,
  REVENUE VARCHAR,
  COVERED_ENCOUNTERS VARCHAR,
  UNCOVERED_ENCOUNTERS VARCHAR,
  COVERED_MEDICATIONS VARCHAR,
  UNCOVERED_MEDICATIONS VARCHAR,
  COVERED_PROCEDURES VARCHAR,
  UNCOVERED_PROCEDURES VARCHAR,
  COVERED_IMMUNIZATIONS VARCHAR,
  UNCOVERED_IMMUNIZATIONS VARCHAR,
  UNIQUE_CUSTOMERS VARCHAR,
  QOLS_AVG VARCHAR,
  MEMBER_MONTHS VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.PAYERS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,
  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,  v[10]::STRING,
  v[11]::STRING, v[12]::STRING,
  v[13]::STRING, v[14]::STRING,
  v[15]::STRING, v[16]::STRING,
  v[17]::STRING, v[18]::STRING,
  v[19]::STRING, v[20]::STRING, v[21]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYERS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************PAYER_TRANSITIONS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.PAYER_TRANSITIONS (
  PATIENT VARCHAR,
  MEMBERID VARCHAR,
  START_DATE VARCHAR,
  END_DATE VARCHAR,
  PAYER VARCHAR,
  SECONDARY_PAYER VARCHAR,
  PLAN_OWNERSHIP VARCHAR,
  OWNER_NAME VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.PAYER_TRANSITIONS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,
  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,  v[7]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_PAYER_TRANSITIONS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

/************************PROCEDURES**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.PROCEDURES (
  "START" VARCHAR, 
  "STOP" VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  BASE_COST VARCHAR,
  REASONCODE VARCHAR,
  REASONDESCRIPTION VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.PROCEDURES
SELECT
  v[0]::STRING,  -- START -> START_TIME
  v[1]::STRING,  -- STOP  -> STOP_TIME
  v[2]::STRING,  v[3]::STRING,
  v[4]::STRING,  v[5]::STRING,  v[6]::STRING,
  v[7]::STRING,  v[8]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_PROCEDURES r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;
/************************PROVIDERS**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.PROVIDERS (
  Id VARCHAR,
  ORGANIZATION VARCHAR,
  NAME VARCHAR,
  GENDER VARCHAR,
  SPECIALITY VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  ZIP VARCHAR,
  LAT VARCHAR,
  LON VARCHAR,
  ENCOUNTERS VARCHAR,
  PROCEDURES VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.PROVIDERS
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,
  v[5]::STRING,  v[6]::STRING,  v[7]::STRING,  v[8]::STRING,  v[9]::STRING,  v[10]::STRING,
  v[11]::STRING, v[12]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_PROVIDERS r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;
/************************SUPPLIES**************************/
CREATE OR REPLACE TABLE CSV_FINAL_ASSIGNMENT.CSV.SUPPLIES (
  DATE VARCHAR,
  PATIENT VARCHAR,
  ENCOUNTER VARCHAR,
  CODE VARCHAR,
  DESCRIPTION VARCHAR,
  QUANTITY VARCHAR,
  SRC_FILENAME VARCHAR,
  SRC_ROW_NUMBER NUMBER
);

INSERT INTO CSV_FINAL_ASSIGNMENT.CSV.SUPPLIES
SELECT
  v[0]::STRING,  v[1]::STRING,  v[2]::STRING,  v[3]::STRING,  v[4]::STRING,  v[5]::STRING,
  r.SRC_FILENAME, r.SRC_ROW_NUMBER
FROM CSV_FINAL_ASSIGNMENT.CSV.RAW_SUPPLIES r,
     LATERAL (SELECT CSV_FINAL_ASSIGNMENT.CSV.PARSE_CSV_LINE(r.RAW_LINE) AS v)
WHERE r.SRC_ROW_NUMBER > 1;

